// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN2_DCkff4mksKB4rBODYgovYYMG2zywI',
    appId: '1:715350488415:web:4e015446fc22b7914ff2ea',
    messagingSenderId: '715350488415',
    projectId: 'watch-me2',
    authDomain: 'watch-me2.firebaseapp.com',
    storageBucket: 'watch-me2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4B6ATiGkWG-lWdyDTeg6FjWTUOKTehJ4',
    appId: '1:715350488415:android:6afbdf3821c12bc34ff2ea',
    messagingSenderId: '715350488415',
    projectId: 'watch-me2',
    storageBucket: 'watch-me2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAStp1AeoiX42cc-vz6J1V_Z9lZOo3ysYA',
    appId: '1:715350488415:ios:48a201a790c920244ff2ea',
    messagingSenderId: '715350488415',
    projectId: 'watch-me2',
    storageBucket: 'watch-me2.appspot.com',
    iosBundleId: 'com.example.watchMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAStp1AeoiX42cc-vz6J1V_Z9lZOo3ysYA',
    appId: '1:715350488415:ios:48a201a790c920244ff2ea',
    messagingSenderId: '715350488415',
    projectId: 'watch-me2',
    storageBucket: 'watch-me2.appspot.com',
    iosBundleId: 'com.example.watchMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN2_DCkff4mksKB4rBODYgovYYMG2zywI',
    appId: '1:715350488415:web:e761ea0ccfe82f394ff2ea',
    messagingSenderId: '715350488415',
    projectId: 'watch-me2',
    authDomain: 'watch-me2.firebaseapp.com',
    storageBucket: 'watch-me2.appspot.com',
  );
}
